server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Prevents NGINX from dropping the port during trailing slash redirects
    absolute_redirect off;
}
